import "../styles/global.css"
import Header       from "../components/header";
import Navigation   from "../components/navigation";
import Footer       from "../components/footer";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout(
    { children, }: { children: React.ReactNode }
) {
    return (
        <html lang="en">
            <body>
                <Header />
                <Navigation />
                    {children}
                <Footer />
            </body>
        </html>
    )
}
